### ISSUE TITLE
Crash on world start 

### ISSUE THREAD

**Issue by darkshadow543** [Sirttas/ElementalCraft#1]
Hello, I am excited to see this new mod in the community.  I was looking forward to trying it out, but I ran into an issue on starting my world.  I got a null pointer exception, and it might be a compatability issue.  Attached is the crashlog which contains the mods I am running in 1.15

[crash-2020-09-05_16.08.20-server.txt](https://github.com/Sirttas/ElementalCraft/files/5178652/crash-2020-09-05_16.08.20-server.txt)

**Comment by Sirttas** [comment]
This issue got reported earlier on discord. It hapen wen a mod add a ore smelting recipe without blasting recipe.

a temporary work around is to set `pureOreSmeltingRecipeInjection` to `false` in your world/serverconfigs/elementalcraf-server.toml

it will be fix in the next update maybe tomorow. don't forget to set the parameter back to `true` after updating.
