### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by LocalBoomer** [Sirttas/ElementalCraft#10]
https://pastebin.com/3Y7cvWCS

Something about a blasting recipe and duplicate keys

MC 1.16.3
forge-1.16.3-34.1.42
ElementalCraft 1.16.3-2.4.0

**Comment by Sirttas** [comment]
Do you have a modpack export ?

**Comment by LocalBoomer** [comment]
Seems to be able to generate a world but crashes after trying to load in, I've deleted all the worlds after each attempt but seems to happen every time I create a new one. export is multiMC but I assume it'll work with Twitch
[dl](https://www.dropbox.com/s/dn7m07mqluzyiyy/1.16.3.zip?dl=1)
I only put the important stuff in as everything else should be default

**Comment by Sirttas** [comment]
fixed in 1.16.3-2.4.1

**Comment by LocalBoomer** [comment]
Can confirm issue gone. Thanks for the quick fix!
