### ISSUE TITLE
Shrines don't properly check shrine upgrades adjacent to them

### ISSUE THREAD

**Issue by cimds** [Sirttas/ElementalCraft#101]
When placing shrine upgrades that have a per shrine limit, the shrine will count all upgrades adjacent to it towards that limit, even if that upgrade is actually connected to another shrine two blocks away. It's possible they even benefit from those upgrades connected to other shrines, which would be another, more unbalanced bug, but I'm not sure how to test that.

Version is 4.4.19, modpack is ATM7.

I really appreciate that you're fixing these bugs I report so quickly, it's kind of amazing.

**Comment by Sirttas** [comment]
Fixed in 4.4.20
