### ISSUE TITLE
[suggestion] upgrades for lumber shrine

### ISSUE THREAD

**Issue by edotenseilove** [Sirttas/ElementalCraft#102]
Hello. I love the new stuff added I know that  lumber shrine is quite new but I think it would be nice to add a range upgrade since as it is now whole tree is not harvested only few logs at the bottom.
and a second upgrade that I would suggest would be a silk touch upgrade(I think it would be a nice and unique addition since not many mods with harvesting options support leaves gathering. I know that leaves usually dont have a lot of uses but I think it would be a nice addition and another reason to use this great mod with mekanism (since leaves can be turned into biofuel).

Have a great day.

**Comment by Sirttas** [comment]
Thanks for this great suggestion. I identify 2 things here:
- the generic upgrades don't work with the 'generic' upgrades (like rang or acceleration). This is because I simply forgot to add them to the compatibility list...
- the compatibility with the silk touch upgrade is a good idea too but wasn't planned at first. I'll add it.

**Comment by Sirttas** [comment]
So I just took a look back at the cod and I did in fact add the lumber shrine to the corresponding tags. So I may have misunderstood your first point. Do you think I should increase the base range of the shrine?

**Comment by edotenseilove** [comment]
The idea behind the first point was that sometimes the tree is not harvested entirely so increasing the range would be a wise decision I think.
![image](https://user-images.githubusercontent.com/19620604/184501601-b9ddb882-9ec4-455c-b2c6-606da5a1d9d7.png)

**Comment by Sirttas** [comment]
I saw that later, And doubled the initial upward range. With a range upgrade or two it should even reach the top of small jungle trees.

**Comment by edotenseilove** [comment]
Thank you have a great day.

**Comment by Sirttas** [comment]
Done in 5.3.1
