### ISSUE TITLE
We like to Affet things

### ISSUE THREAD

**Issue by phorced** [Sirttas/ElementalCraft#103]
**Describe the bug**

**To Reproduce**
1 install JEI
2 install elemental craft
3 search protection shrine upgrade
4 Read how it "Only (Affet) hostiles"

**Expected behavior**
Would say only affet hostiles
Should say only effects hostiles

**ModPack**
Any that has JEI and elemental craft

**Comment by phorced** [comment]
:D was looking for affix and found it

**Comment by Sirttas** [comment]
Fixed a fex versions ago, I forgot to close this.
