### ISSUE TITLE
Pure ore chunks do not smelt 

### ISSUE THREAD

**Issue by Mistmage** [Sirttas/ElementalCraft#105]
**Describe the bug**
pure ore chunks not smelting in normal furnaces, including elemental craft ones.
Mekanism processing works fine.
I am using elementalcraft-1.18.2-4.4.22

**To Reproduce:**
1. enter in the world
2. see "Tried to load unrecognized recipe" things in logs
3. get any pure ore chunk
4. put it in any vanilla, create or elemental craft furnace (not mekanism one)
5. add fuel
6. See error.

I want to add that I have seen two more mods with “Tried to load unrecognized recipe” things, but they recipe seems to work fine.

**Expected behavior**
smelt properly

![2022-09-02 11-54-01 Minecraft  1 18 2 - Singleplayer](https://user-images.githubusercontent.com/42159697/188103098-bcbd0e09-cbe9-4ad4-9b1c-e8fd577f0cf5.png)

Smelting properly.

[Mistmage's pack-1.3.zip](https://github.com/Sirttas/ElementalCraft/files/9476493/Mistmage.s.pack-1.3.zip)

**Comment by Sirttas** [comment]
Remove FastSuite: https://github.com/Shadows-of-Fire/FastSuite/issues/15

**Comment by Sirttas** [comment]
Nevermind I font what I did wrong on my part

**Comment by Mistmage** [comment]
Thanks!

**Comment by Sirttas** [comment]
fixed in 4.4.23
