### ISSUE TITLE
1.19.2 client crash when opening loot chests

### ISSUE THREAD

**Issue by Daltaxy** [Sirttas/ElementalCraft#106]
**Describe the bug**
1.19.2, last mod version from 9/2/2022. The game crashes when I try to open random loot chests. I had already opened the chests before. When I download the mod to its version before the last one, so from 5.4.0 to 5.3.4, I can open the chests with no issue.

**To Reproduce**
1. Go to Multiplayer, join the server (hosted on my own pc, so dedicated server)
2. Right-Click on any loot chest (tried two times with two loot chests)
4. See crash happening right after chest opening sound.

**Expected behavior**
No crash when opening the chests

**ModPack**
Either a known pack (ex: ATM6) or a Twitch/MultiMC export
GD Launcher modpack made by myself

Finally, I have the latest.log which mentioned the mod using a duplicate netherite item or something. I do not have a debug.log as it is hard to get with GD Launcher, but latest.log seems enough as I could spot the issue after reading through it. I can try giving you a debug.log if you really need it, by retrying
https://gist.github.com/Daltaxy/3a7f79d19685045ac7312d8a029e6d85
Edit: typo

**Comment by Daltaxy** [comment]
oh and I don't know if it matters but I was invisible before opening the loot chests, using the Ability Bottle.

**Comment by Sirttas** [comment]
fixed in 5.4.1
