### ISSUE TITLE
Duplicate Recipe error upon rejoining server

### ISSUE THREAD

**Issue by Mrbysco** [Sirttas/ElementalCraft#107]
**Describe the bug**
When re-connecting to a server with Elemental Craft that you already connected to before you get kicked for duplicate recipes

**To Reproduce**
1. Create a server with Elemental Craft and it's required dependencies
2. Boot up the server
3. Connect to the server with a client
4. Disconnect from the server
5. Reconnect to the server
6. Get booted with a duplicate recipe error

**Expected behavior**
Being able to rejoin a server after disconnecting for a bit

**Logs**
https://gist.github.com/Mrbysco/9035ff73e1b646737ec19e905bc6ee4d

**Comment by Sirttas** [comment]
Fix in 5.4.1.
