### ISSUE TITLE
Elementopedia not exist and Source Receptacle item don't have craft

### ISSUE THREAD

**Issue by SoloJean** [Sirttas/ElementalCraft#108]
Hi. Firstly, sorry for my english.
I play currently in 1.19.2 version
I have a issue, i don't have item elementopedia and item source receptacle, it's normal or it's a bug? please help me:(
I mean, source receptacle don't have craft and elementopedia only not exist

thank u

**Comment by Sirttas** [comment]
In 1.19 sources are moved with a source displacement plate.
