### ISSUE TITLE
Persistent zombie accumulation

### ISSUE THREAD

**Issue by Kmaput** [Sirttas/ElementalCraft#109]
**Describe the bug**
Zombies pick up water shards dropped by glow squids naturally dying in caves, which causes them to become persistent. Over time they accumulate and cause significant performance issues. Basically the same as [MC-227300](https://bugs.mojang.com/browse/MC-227300).

**Expected behavior**
Zombies should not be able to pick up elemental shards.

**Comment by Sirttas** [comment]
I really don't like how mojang fixed it... And I think I will make a forge PR to clean it up a bit. In any case thanks for the bug report, I will fix it once I get time during my vacation or once I get back home.

**Comment by Sirttas** [comment]
fixed in 4.4.27 for 1.18.2. It will be ported to 1.19.2 later.
