### ISSUE TITLE
Dispenser activation crashes game when crystals are in them

### ISSUE THREAD

**Issue by mosharky** [Sirttas/ElementalCraft#11]
Jungle Temples spawn with crystals in their dispensers, and when a mob or a player trips the tripwire, redstone activates the dispensers. This led to the server crashing. I checked out the loot tables this mod adds but it seems like it injects them. Is there any way I can blacklist the jungle temple dispenser?

I've already found the file path for it (minecraft:chests/jungle_temple_dispenser)

**Comment by Sirttas** [comment]
fixed in 2.4.5
