### ISSUE TITLE
Air Mill Duplication

### ISSUE THREAD

**Issue by Benny-Boo** [Sirttas/ElementalCraft#110]
**Describe the bug**
When you break the Element Container under an Air Mill, it drops two Air Mills.

**To Reproduce**
1. Place an Element Container
2. Place an Air Mill on top
3. Break the Element Container
4. Profit

**Expected behavior**
Not duplicate lol

**ModPack**
ATM7

**Comment by Sirttas** [comment]
fixed in 4.4.27 for 1.18.2. It will be ported to 1.19.2 later.
