### ISSUE TITLE
Binder, Infuser, Inscriber get item from left hand.

### ISSUE THREAD

**Issue by uhloin** [Sirttas/ElementalCraft#113]
If right hand is empty then right click removes shield from left hand and puts into binder, inscriber, infuser etc. 
There is no sense to do it. Moreover it may be done imperceptibly and later player will not understand why shield disappeared.

**Comment by Sirttas** [comment]
What version are you on?

**Comment by uhloin** [comment]
elementalcraft-1.19.2-5.4.6.jar

**Comment by Sirttas** [comment]
Fixed in 1.19.2-5.5.1
