### ISSUE TITLE
Elementopedia misprints

### ISSUE THREAD

**Issue by uhloin** [Sirttas/ElementalCraft#116]
Thank you very much for version elementalcraft-1.19.2-5.5.1.jar
There are minor misprints or skips in updated Elementopedia, I attached fixes.
Also I suppose jewel of Leopard should be renamed to jewel of Guepard (or Cheetah) because leopards are not such fast runners but very good jumpers.

**Comment by Sirttas** [comment]
Thank you! I can't find the attached file. where is it?

**Comment by uhloin** [comment]
I retry...
[book.zip](https://github.com/Sirttas/ElementalCraft/files/9704034/book.zip)

**Comment by Sirttas** [comment]
fixed in 5.5.2
