### ISSUE TITLE
New Repair spell

### ISSUE THREAD

**Issue by uhloin** [Sirttas/ElementalCraft#117]
It is not found in book and scroll does not work... or I did not found a way. I tried use it on damaged item in inventory, on dropped, on moved to left hand on putted to frame and even on damaged anvil :)

**Comment by Sirttas** [comment]
I forgot to add it. You need to have the item you want to repair in your second hand and target a block on the ground.

**Comment by uhloin** [comment]
OK, I used it on netherite pickaxe. When you will describe it in Patchouli please do not forget say that need press-and-hold right button or else if just click then there is only tiny repair and wait 120 s after.

**Comment by Sirttas** [comment]
yeah I need to define what channeled spells are.

**Comment by Sirttas** [comment]
Fixed in 5.6.0
