### ISSUE TITLE
'Crash' after server startup and loaded a source node - running version 5.5.3

### ISSUE THREAD

**Issue by Mowmaster** [Sirttas/ElementalCraft#118]
**Describe the bug**
https://pastebin.com/wVJ2tjzq

Server has the forge config set to remove erroring Entities/BE's and when it does it usually sends a report in the console, i happened to look and saw this (this is after i started playing with the mod on the server doing the normal steps)

**ModPack**
ATM8 - 0.1.4

**Reproduce**
the setup i have is this at 4 nodes on the server
![image](https://user-images.githubusercontent.com/10681506/196795591-7747fafa-c3f3-4839-ae4d-d3ca25495549.png)
 no idea if this is actually reproduceable, but hopefully this helps if you do try it.

**Comment by Sirttas** [comment]
Fixed in 5.5.4
