### ISSUE TITLE
Inert crystal ore can be mined with any pickaxe

### ISSUE THREAD

**Issue by Nevrai** [Sirttas/ElementalCraft#119]
Inert crystal ore can be mined with any pickaxe (even wooden pickaxes) despite having a mining level of iron. Even when The One Probe shows a red ×, implying you can’t mine this ore, it still drops inert crystals upon mining them.

I have tested this in both 1.18.2 and 1.19.2 with the latest versions of Forge and ElementalCraft. Occurs in both.

### Versions
* **Minecraft:** 1.19.2
* **Forge:** 43.1.43 (latest)
* **ElementalCraft:** 5.5.3 (latest)

**Comment by Sirttas** [comment]
Fixed in 5.5.4
