### ISSUE TITLE
Crash on loading second world [java.lang.IllegalStateException: Duplicate key net.minecraft.item.crafting.BlastingRecipe]

### ISSUE THREAD

**Issue by Goldenlion5648** [Sirttas/ElementalCraft#12]
[crash-2020-11-08_00.25.57-server.txt](https://github.com/Sirttas/ElementalCraft/files/5505874/crash-2020-11-08_00.25.57-server.txt)
mod version: 2.4.3

**Comment by Sirttas** [comment]
fixed in 2.4.5
