### ISSUE TITLE
Silent gear and jewels

### ISSUE THREAD

**Issue by uhloin** [Sirttas/ElementalCraft#120]
Version 1.19.2

Looks like you care about compartibility with Silent Gear but I cannot set Jewel of Demiod on Silent Gear's armor. Do not know about other jewels.

**Comment by Sirttas** [comment]
That's because in 1.19.2 there is a `forge:armors` tag (and derivatives ex: `forge:armors/boots` and this tag is used to determine if an item can receive jewels or not.

**Comment by uhloin** [comment]
I.e. it is SG's issue? Should I report them it as a bug?

**Comment by Sirttas** [comment]
Yes.

**Comment by uhloin** [comment]
Could you say if this glitch in the name of the sword is also issue of SG or yours bug?

**Comment by uhloin** [comment]
![2022-11-07_17 43 18](https://user-images.githubusercontent.com/96169906/200325662-5b5651f8-ee17-4577-b119-2e1df8878dff.png)

**Comment by uhloin** [comment]
Could you expand list of forge tags to allow jewels? For example, all "forge:shield". I can send you list of usual tags from SG.

**Comment by Sirttas** [comment]
`forge:shield` is not the official forge tag, it is `forge:tools/shields`

**Comment by uhloin** [comment]
Therefore I ask may be it's not bad idea to expand list of additional tags from various most popular mods then wait for their fixes. Small change big effect = profit :)
