### ISSUE TITLE
Can you upload this mod in a maven repository?

### ISSUE THREAD

**Issue by Mineablechn** [Sirttas/ElementalCraft#125]
Thanks a lot!
Here are some maven repositories:
https://maven.blamejared.com/
https://dvs1.progwml6.com/files/maven

**Comment by Sirttas** [comment]
Hi, elemental craft can be found on the following repositories:
https://repo.elementalcraft.org/#/public (mirror from: https://repo.elementalcraft.org/#/releases)
https://modmaven.dev/
