### ISSUE TITLE
[ATM8 1.0.8] Elemental Reservoir Breaking

### ISSUE THREAD

**Issue by Jophire** [Sirttas/ElementalCraft#128]
**Describe the bug**
When breaking an elemental reservoir, if the top block is mined, the item will not drop.
If the bottom block is mined, the reservoir item is dropped.

**To Reproduce**
Place elemental reservoir. (we were using earth ones at the time.)
Break the top block.
No item is dropped.

**Expected behavior**
Reservoir item drops.

**ModPack**
ATM8 1.0.8

**Comment by Sirttas** [comment]
Fixed in 5.5.9
