### ISSUE TITLE
Binder not working.

### ISSUE THREAD

**Issue by alcheya** [Sirttas/ElementalCraft#129]
Reactions in Binder not starting.

**To Reproduce**
Place a binder on a full container of the required element, in my case both Air and Water. Put the ingredients in the correct order. 

**Expected behavior**
There should be particle effects and swift alloy should be the result. Instead, nothing happens. 

**ModPack**
ATM8 with manual (curseforge managed) upgrade to 5.5.7

**Comment by Sirttas** [comment]
duplicate of #127
