### ISSUE TITLE
The specified resource 'elementalcraft.mixins.json' was invalid or could not be read

### ISSUE THREAD

**Issue by gamma-delta** [Sirttas/ElementalCraft#13]
Hello, I'm getting a crash with ElementalCraft. The important part seems to be `The specified resource 'elementalcraft.mixins.json' was invalid or could not be read`.

[Here's the full crash report.](https://pastebin.com/w2fXfJ7p)

Mods installed are:
```
  [✔️] BiomesOPlenty-1.16.4-13.0.0.420-universal
  [✔️] create-mc1.16.3_v0.3+custom
  [✔️] elementalcraft-1.16.3-2.4.5
  [✔️] ImmersiveEngineering-1.16.4-4.1.1-128
  [✔️] inventorysorter-1.16.1-18.1.0
  [✔️] jei-1.16.4-7.6.0.57
  [✔️] kubejs-1604.3.1.79
  [✔️] Mekanism-1.16.4-10.0.17.444
  [✔️] modnametooltip_1.16.2-1.15.0
  [✔️] MouseTweaks-2.13-mc1.16.2
  [✔️] Patchouli-1.16.2-47
  [✔️] pneumaticcraft-repressurized-1.16.3-2.5.0-66
  [✔️] Quark-r2.4-275
```

I had loaded this instance before with BluePower, but deleted the mod. It did not crash before I deleted BluePower.

I'm on 1.16.4.

Thank you for helping!

**Comment by gamma-delta** [comment]
wow you're fast

**Comment by Sirttas** [comment]
This bug hapened the other day  for all the mods 6, this bug is due to some mods fucking something preventing mixins to load properly.

Could you retry without elementalcraft an see if you get the same eror for another mod mixins ?

**Comment by gamma-delta** [comment]
Sure, here you go: https://paste.ee/p/wMVBC

It looks like it's now a problem with KubeJS...

**Comment by Sirttas** [comment]
try each mods individualy, I don't see another solution, or directly ask help in sponge discord. Since it's not directly linked to elementalcraft, and I cannot fix it so I will close this issue.

**Comment by gamma-delta** [comment]
OK, thank you for trying to help.

**Comment by gamma-delta** [comment]
I forgot to install Rhino (KubeJS depends on it). So it wasn't an issue with you at all! sorry...

**Comment by Sirttas** [comment]
It's a bug with forge I think.
