### ISSUE TITLE
Index 5 out of bounds for length 5 crash

### ISSUE THREAD

**Issue by deguix** [Sirttas/ElementalCraft#130]
**Describe the bug**

Crash log: https://pastebin.com/61edXf2H (1 month exp)

(1 bug and 1 bug/crash) I was using Refined Storage to auto-craft Swift Alloy Ingot at the same time it was already crafting Air Crystal on the same Improved Elemental Binder (I realized it later it was a really bad idea). The inert crystal was sent in first, then on next tick, items belonging to Swift Alloy Ingot got sent in, except the last Air Crystal, because there weren't any left. Even with 5 items on the binder, it successfully crafted an Air Crystal, and the resulting Air Crystal got placed at the end of the list on the binder. Because the Ultra Importer was whitelisted on Air Crystal, it got imported to RS as it was starting to craft the Swift Alloy Ingot, and that resulted in the crash.

This is how I setup the RS auto-crafting system on it (I don't know if it's needed, but here it is):
- Ultra Importer on top whitelisted on all products of improved elemental binder.
- Diamond Crafter on the side, set to "Redstone signal unlocks autocrafting".
- Comparator on the side of the binder, and redstone in front of it - on the wall on the side of comparator was a redstone torch, another red stone dust, and LaserIO's node with side closest to dust set to take in redstone signal, ouput to Crafter wtih strong signal (I forgot how it's called).

**To Reproduce**
1. Setup RS Importer whitelisted on Air Crystal and facing Improved Elemental Binder.
2. Put Inert Crystal on Improved Elemental Binder with Air element.
3. Right after, while Air Crystal is being crafted, put Swift Alloy Ingot ingredients on it except for Air Crystal.
4. Once Air Crystal is made (which is 1 bug already), and if RS imports it fast enough to RS system, a crash should happen.

Should also happen to other recipes that depend on recipes from Element Infuser.

**Expected behavior**
Air Crystal not being made at all if other items are placed there. This should prevent crash as well, but unfortunatelly I can't play on my save because of the crash.

**ModPack**
ATM8 1.0.8 with ElementalCraft 5.5.8 (it comes with older EC but I updated it to this to make Elemental Binder work).

**Comment by deguix** [comment]
I updated to 5.5.9 and used amulet mc to delete the binder, and got it back. I haven't managed to reproduce the crash since then. But the elemental crystals being made while other items are there with an importer messes up everything. Visually things get messed up, sometimes it looks as though there are no items there, but there are after an elemental crystal was just made and imported.

**Comment by Sirttas** [comment]
I saw the issue in the code so it is still here.

**Comment by deguix** [comment]
yes, managed to make it crash again just now. ^^

**Comment by deguix** [comment]
I have some more crashes from having an importer on a rune inscriber while attempting to semi-auto-craft runes (which once again I forgot to whitelist the proper runes on the importer). The error says: "java.lang.IllegalStateException: The internal crafting inventory reported that 1 string was available but we got 9523 air" - a RS error. At that moment I was trying to craft Fus Rune, and I just sent an order to craft it, and I was in front of rune inscriber, but it was an insta crash. Trying to run game again just errors with "java.lang.IllegalStateException: Bad!" Sure hope I didn't mess up RS too hard ;/.

Crash log at: https://pastebin.com/3YRJYaHf.

Using ATM8 1.0.9 now.

**Comment by Sirttas** [comment]
This looks like a strange behavior from RS to crash here.

Please report this issue to RS.

**Comment by Sirttas** [comment]
fixed in 5.5.10
