### ISSUE TITLE
Minor spelling error

### ISSUE THREAD

**Issue by MindBrain27** [Sirttas/ElementalCraft#131]
**Describe the bug**
Pure Redstone Ore Chunk is missing the d in Redstone, it reads as Pure Restone Ore Chunk.

**To Reproduce**
See tooltip for spelling of Pure Redstone Ore.

**Expected behavior**

**ModPack**
Custom

**Comment by prasadj2003** [comment]
could you provide the location of the file

**Comment by Sirttas** [comment]
@predatorprasad I has ben fixed but not yet released.

**Comment by prasadj2003** [comment]
Ok

**Comment by Sirttas** [comment]
Fixed in 5.6.0
