### ISSUE TITLE
My list of suggestions/bugs

### ISSUE THREAD

**Issue by deguix** [Sirttas/ElementalCraft#132]
(while playing on ATM 8)
- Remove "Other", "End" and planet names of Ad Astra from Pure Chunks names.
- Prevent removing runes if holding right click with Rune Inscription Chisel on Rune Inscriber (needs to require shift first).
- Add recipes to convert raw block recipes from Ad Astra, Allthemodium, and Silent Gear mods to pure chunks.
- Add elemental infusion recipes on Silent Gear stuff and Mystical Agradditions Paxels.
- Add jewel forging recipes on Silent Gear stuff.
- Add Certus Quartz Shrine Upgrade.

Maybe I could try getting some of them up, one of these days.

**Comment by AlleCraft-alterego** [comment]
elemental infusion recipes on Silent Gear stuff and Mystical Agradditions Paxels is a problem of tags (this mods don't use official forge tags but a variant like cyclic)

**Comment by Sirttas** [comment]
I fixed the majority of the points you reported here in 5.6.0. The only remaining points are:

> Add elemental infusion recipes on Silent Gear stuff and Mystical Agradditions Paxels.
> Add jewel forging recipes on Silent Gear stuff.
> Add Certus Quartz Shrine Upgrade.

That either fall on pack dev or require a full interraction to be implemented.
