### ISSUE TITLE
doing /reload causes a "fail"

### ISSUE THREAD

**Issue by redgoblin88** [Sirttas/ElementalCraft#133]
upon having the listed mods below downloaded (no more, no less), start the game, make (or join) a world and type /reload, this should reload all the datapacks/recipes however it "fails" and reverts back to old data
however, note that if you have added something via datapack (for example, adding/changing something VIA kubejs such as "dirt to diamond" recipe added) and then close the game and re-launch it, the "failed" recipe from last test is now working and loaded up (until you use the command again)

mods used...
- forge: 43.2.8
- elementalcraft: 5.5.10
- DataPack Anvil: 4.3.1
- immersive engineering: 9.2.0-162
logs: https://pastebin.com/PSU9PhBw

**Comment by Sirttas** [comment]
Fixed in 5.6.0
