### ISSUE TITLE
Ordered Sorter is not shown when got swift alloy

### ISSUE THREAD

**Issue by uhloin** [Sirttas/ElementalCraft#135]
Probably after I got swift allow patchouli book should get topic "Ordered Sorter". 
I can see it in JEI but not as normal receipt advancement.

**Comment by uhloin** [comment]
May be I made mistake. Now found it in Advanced Part but waited among Instruments. Not sure when it appeared.

**Comment by Sirttas** [comment]
The sorter and the retriever are both in the advanced category. I retested it and it seems to be working fine.
