### ISSUE TITLE
(improvement) Crystal grow upgrade shoud effect on crystal shrine

### ISSUE THREAD

**Issue by uhloin** [Sirttas/ElementalCraft#136]
I created a Budding Shrine with Springaline Shrine Upgrade and set near a Growth Shrine with Crystal Grow Shrine Upgrade to get x30 speed of crystal grow... but failed :) Should such pair of shrines work together?

**Comment by Sirttas** [comment]
This is an intended behavior. The idea is that no shrines can affect the action of another one.
