### ISSUE TITLE
Fluorite pure ore chunks smelt into Aluminum

### ISSUE THREAD

**Issue by gamma-delta** [Sirttas/ElementalCraft#14]
I'm playing with ElementalCraft, Mekanism, and Immersive Engineering. For some reason, Pure Fluorite ore chunks smelt into IE's Aluminum Ingots. Bauxite chunks don't smelt into anything at all.

**Comment by Sirttas** [comment]
Could you verify that Bauxite is in the `forge:ore` tag, I would also like to have a modpack export.

**Comment by Sirttas** [comment]
fixed in 2.4.9
