### ISSUE TITLE
Overload Shrine does not appear to do anything

### ISSUE THREAD

**Issue by TronWoWGamer** [Sirttas/ElementalCraft#141]
**Describe the bug**
I crafted an overload shrine, that is being fed air source from a container, one of the really big ones which is in turn being fed from two of the regular containers that have extractors on them.  All containers are full of source.  I put a shrine on each of my Phytogenic Insulators from Thermal and they seem to be attached.  I have all pipes hooked up between shrines and containers.  I have added upgrades for capacity and optimization.  The speed of the machines is not changing.

I also tried this on a hopper botany pot and my seeds did not grow faster.

**To Reproduce**
See above

**Expected behavior**
I expected the same type of tick acceleration that I get from Time in a Bottle

**ModPack**
This is on TNP Limitless 6 (MC 1.19.2)

**Comment by Sirttas** [comment]
It's not crazy OP, its a passive tick accelerator, You need acceleration shrine upgrades if you want to reach x5 speed.
