### ISSUE TITLE
Fire pylon duplication (possibly others)

### ISSUE THREAD

**Issue by Saereth** [Sirttas/ElementalCraft#145]
**Describe the bug**
Placing down and breaking a firepylon results in 2 blocks being dropped

**To Reproduce**
1. Place down a fire pylon
2. mine it
3. collect 2 fire pylons

**Expected behavior**
Not duping

**ModPack**
FTB Skies

https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3358

**Comment by Sirttas** [comment]
fixed in 5.8.5
