### ISSUE TITLE
ore shrine don't work 1.18.2

### ISSUE THREAD

**Issue by ComeBelin** [Sirttas/ElementalCraft#147]
i deposit a ore in the world but the ore shrine doesn't work. 
the shrine with fill 
 earth and the other srhine works with my pipes.
![2023-06-12_16 46 53](https://github.com/Sirttas/ElementalCraft/assets/48830039/fa65f1c4-2e5a-4303-8b60-716d167d410c)

**Comment by Sirttas** [comment]
According to your screenshot there is multiple things on the pipe, make sure element s reaching the shrine.

**Comment by ComeBelin** [comment]
![image](https://github.com/Sirttas/ElementalCraft/assets/48830039/85659039-68a6-450e-87bd-43a56d099ed9)
it's full

**Comment by Sirttas** [comment]
Fixed in 6.1.0
