### ISSUE TITLE
Pure infuser crashes on multiplayer

### ISSUE THREAD

**Issue by jinkhya** [Sirttas/ElementalCraft#15]
Hello, 
Currently playing ATM6 and somebody placed a diamond on a pure infuser which crashed instantly. 
Modpack version 1.3.0
Forge : 35.0.14
ElementalCraft : 2.4.6

Here's the crash log : 
https://gist.github.com/jinkhya/9cd04ff25016798e463aba64b0c2eeb9

**Comment by Sirttas** [comment]
fixed in 2.4.7
