### ISSUE TITLE
mana element syntesizer bug 1.18.2

### ISSUE THREAD

**Issue by ComeBelin** [Sirttas/ElementalCraft#150]
1) the guide book of mod has a problem because he repeat the information of the solar element synthesizer.
2) he don't have a utility or the item is bug ? because it don't have a utility on JEI

**Comment by Sirttas** [comment]
I don't understand what you means in 2

**Comment by ComeBelin** [comment]
sorry 2 is a error sorry

**Comment by Sirttas** [comment]
Fixed in 6.1.0
