### ISSUE TITLE
Place Element source in Nether

### ISSUE THREAD

**Issue by IdaEdz** [Sirttas/ElementalCraft#153]
**Describe the bug**
If I place a Element Source in the Nether it turns into a Water Source Element (shows as blue)

**To Reproduce**
1. Go to the Nether
2. Click on the ground with a Element Source
3. See a Water Source

**Expected behavior**
I am expecting to see a Fire Source Element

**ModPack**
The mod is in the FTB Skies modpack 

**Versions and stuff**
Minecraft - 1.19.2
FTB Skies Modpack - 1.3.1
ElementalCraft - 5.8.5

**Picture**
[Imgur link to picture from my world.](https://imgur.com/a/K3UQLbA)

**Comment by Sirttas** [comment]
You are using the source item, it is a **creative** item used to add a source in the world regardles of biome. FTB skies allows player to get acces to it.
