### ISSUE TITLE
Elementopedia has Invalid ID

### ISSUE THREAD

**Issue by Crazydude323** [Sirttas/ElementalCraft#155]
When loading into the game and opening up the creative menu, the Elementopedia is shown as "Guide Book" in the creative tab, along with a tooltip that the no ID was defined. The Elementopedia does not show up in JEI at all.

I can only assume that this is a compat issue, but what would be causing the issue I've no idea on. I can see about exporting the pack, and testing things myself, when I have some time to spare. But I figured I ought post this earlier rather than later, just in case.

![2023-12-01_21 43 13](https://github.com/Sirttas/ElementalCraft/assets/60992786/b6250b75-a92e-4654-9680-6ae4c72f8239)

**Comment by Sirttas** [comment]
Fixed in 6.1.0
