### ISSUE TITLE
Patchouli book broken at initial Inner Crystal stage

### ISSUE THREAD

**Issue by alfonsan** [Sirttas/ElementalCraft#156]
**Describe the bug**
Initial steps of the mod, already a few stacks of ore mined, already a few stacks of elements gathered. Opened book (inside eccentric tome), I cannot get passed the initial ore entry. Quest book showing a brown icon on the right with no further description. Tried everything I could figure out, new book outside of eccentric tome, didnt worked. Mine with silk touch, didnt worked, mine with a regular iron pickaxe, didnt worked. It remains stucked at the initial stage.

**To Reproduce**
I think previous description already detailed this point.

**Expected behavior**
Reading the chapter, or mining some ore, or having some ore in players inventory, should mark the chapter as complete and unlock next chapters.

**ModPack**
Just a bunch of mods gathered by me.

Forge: 1.20.1 47.2.17
Mod Elemental Craft: 1.20.1 6.0.1

![2024-01-06_13 55 18](https://github.com/Sirttas/ElementalCraft/assets/2581625/6ad0b09a-505b-4065-bc5f-05a0033ec45c)
![2024-01-06_13 55 20](https://github.com/Sirttas/ElementalCraft/assets/2581625/414cc54f-9a7f-4744-9cc2-4ad9f180a0e0)
![2024-01-06_13 55 22](https://github.com/Sirttas/ElementalCraft/assets/2581625/184e3129-35dc-42aa-becc-824d21a7bfd9)

**Comment by Sirttas** [comment]
Fixed in 6.1.0

**Comment by HockeyZman2000** [comment]
Could you please backport the fix for this to 1.20.1 as well?

**Comment by Sirttas** [comment]
> Could you please backport the fix for this to 1.20.1 as well?

Sadly no, I no longer have an environment ready for 1.20.1.

**Comment by Shinnonda** [comment]
any way to force to complete it using commands or something?
or just disable the progress at all, cause i'm using it in a modpack, and some of them are not on 1.20.4. if i can just force it to be all unlocked would be less problematic than wait until all mods update/be comaptible to each other on 1.20.4.

**Comment by Reaperjm** [comment]
> any way to force to complete it using commands or something? or just disable the progress at all, cause i'm using it in a modpack, and some of them are not on 1.20.4. if i can just force it to be all unlocked would be less problematic than wait until all mods update/be comaptible to each other on 1.20.4.

You can goto patchouli mod config and add elementalcraft:element_book under No Advancement Books. This can be done in game in the mod config pause menu. No restart needed. This will remove all advancement from the book so you can use it. It bugged me and I knew there had to be a way to turn off advancement. Hope this helps.
