### ISSUE TITLE
[1.16.4] Crash when clicking on item with info tab but no craftable recipe

### ISSUE THREAD

**Issue by ViRb3** [Sirttas/ElementalCraft#17]
Modpack: ATM6 1.3.2
Mod: elementalcraft-1.16.3-2.4.10.jar
Forge: forge-35.1.3

I used KubeJS to disable crafting of a problematic item, unrelated to ElementalCraft. I also added JEI information about why it was removed. The result is when you click on the item, you see only one tab - the info tab - and no crafting recipes.

With ElementalCraft added, the game crashes as soon as I click on the item. Log: https://mcpaste.io/26452dc352b3acc0

**Comment by jeremiahwinsley** [comment]
https://github.com/Sirttas/ElementalCraft/blob/99eb93102f9fb24027e1bf0f72075c0b54e7e24b/src/main/java/sirttas/elementalcraft/interaction/jei/ingredient/element/ElementIngredientRenderer.java#L19
 `ingredient` here is not checked before use, but [IIngredientRenderer](
https://github.com/mezz/JustEnoughItems/blob/cbe18a83dbafc220ad90d3e80a2031311565cd09/src/api/java/mezz/jei/api/ingredients/IIngredientRenderer.java#L29) can pass null here:

```java
void render(MatrixStack matrixStack, int xPosition, int yPosition, @Nullable T ingredient);
```
