### ISSUE TITLE
Can't seem to craft pure crystal as described in manual?

### ISSUE THREAD

**Issue by JustJinxed** [Sirttas/ElementalCraft#20]
**Describe the bug**
Can't seem to craft pure crystal as described in manual?

**To Reproduce**
1. Place each of the four alters and pure infuser using the book to guide, got 100% and complete
2. attached each altar with 1 pipe on the outside face and attached corresponding full tank of elements
3. placed in order fire, air, earth, water, on corresponding altars, and a diamond on the infuser
4. nothing is happening.

**Expected behavior**
I'd imagine I'm supposed to get a pure crystal?

**ModPack**
All the mods 6 (elementalcraft-1.16.3-2.4.8)

**Comment by Sirttas** [comment]
have you configured the pipes as extracting ?

**Comment by JustJinxed** [comment]
I didn't.. LOL oh my goodness.. close this? I can't believe I didn't think of that. (it's working now)
