### ISSUE TITLE
Updated en_us.json file

### ISSUE THREAD

**Issue by GrokDuckFarmer** [Sirttas/ElementalCraft#21]
Attached is an updated en_us.json file with many grammar and spelling fixes.  I can't promise that I caught them all, but I did catch most of them.

[en_us.json.txt](https://github.com/Sirttas/ElementalCraft/files/5620417/en_us.json.txt)

(Renamed .txt because GitHub didn't like the .json extension.)

**Comment by Sirttas** [comment]
thank you for your work, I transformed your file into a pull request (https://github.com/Sirttas/ElementalCraft/pull/22) to better see the changes you have done. I also recomand you to do PRs because it simplify the work for the author and add your name to the contributors list on github.

**Comment by GrokDuckFarmer** [comment]
That means learning Git commands.  :)

**Comment by Sirttas** [comment]
in 2.4.13
