### ISSUE TITLE
Feature requests: Finding Element Sources easier

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [Sirttas/ElementalCraft#23]
We here on the AllTheMods discord have a few feature requests for your fantastic mod. 

1. Elemental sources should emit light. (light level 7 or below? Think silent gems glow roses)
1b. Elemental Sources should render farther away. 

Please consider our request and thank you for your time. Happy Modding, and happy holidays.

**Comment by kill05** [comment]
I'm a bit late but whatever. You can find element sources easily by looking on the map. If you look closely there are some black dots, that represent nodes.

**Comment by Sirttas** [comment]
This will be part of 2.6, there is already a snapshot on curseforge.
