### ISSUE TITLE
[1.16.4] Crash when clicking on ElementalCraft's creative tab button

### ISSUE THREAD

**Issue by TelepathicGrunt** [Sirttas/ElementalCraft#24]
When using only elementalcraft-1.16.3-2.4.16 on 35.1.13 Forge in 1.16.4 MC, clicking the creative tab for ElementalCraft crashes the game. Here's the latest.log file:
[latest.log](https://github.com/Sirttas/ElementalCraft/files/5725545/latest.log)
https://hastebin.com/uhasukohuv.properties

All I did was create a fresh new world in Creative, put a Dispenser, Stone Button, and Redstone Wire into my inventory, and then clicked on ElementalCraft's creative tab and crashed. 

Once this is fixed, I can test Dispenser behaviors with ElementalCraft and my mod Blame on to see if my mod has a mod conflict bug or not. Hopefully the creative tab can be fixes easily!

**Comment by Sirttas** [comment]
You need jei to be installed

**Comment by TelepathicGrunt** [comment]
Oh I see the required dependencies. My bad. Though you can set mandatory to true for jei and patchouli here so players will get the screen saying to download those dependencies. 
https://github.com/Sirttas/ElementalCraft/blob/83540c5344a9ec0b548cc3425c686cf671b641ce/src/main/resources/META-INF/mods.toml#L21

**Comment by Sirttas** [comment]
Yeah, it shouldn't be mandatory but I'm using JEI code and I forgot to check if jei is here or not that caused the crash. That's why I am not closing this issue until it's fixed.

**Comment by Sirttas** [comment]
Looking back a the issue there was also a problem with patchouli, it's fix in next update.

**Comment by Sirttas** [comment]
fixed in 2.4.17
