### ISSUE TITLE
Workng around this mod is really laggy

### ISSUE THREAD

**Issue by lasiecz** [Sirttas/ElementalCraft#25]
Hello there,

I am playing All the Mods 6 1.16.4 with Elemental Craft version 2.4.16 - but it so laggy then i cant walk aroud it. I've set up simple furnace and my FPS (while walking around it) dropped from 120FPS (I have capped FPS to 120) to 20FPS.

My setup:
GeForce RTX 2070 Super
32GB RAM
AMD Ryzen 5 3600

![2020-12-30_11 35 29](https://user-images.githubusercontent.com/12786747/103346022-37b21e00-4a93-11eb-8497-e6d75a93e7ab.png)

Any tips?

**Comment by Sirttas** [comment]
Do you have optifine or other optimization mod installed ?

**Comment by lasiecz** [comment]
Well its part of the All The Mods 6 pack so I dont know and I didnt find Optifine (dont know what other mods are for optimization that I should search for).

PS: the game was runing fine before I started playing aroud this mod

EDIT: Its only laggy when the element is extracting to the container so the particles

**Comment by Tenchu98** [comment]
If the " out of sight" mod is in your version, try removing it
Apparently it can have the opposite effect when combined with certain mods.

**Comment by lasiecz** [comment]
"out of sight" not in the modpack sadly

**Comment by lasiecz** [comment]
> If the " out of sight" mod is in your version, try removing it
> Apparently it can have the opposite effect when combined with certain mods.

nope, this mod is not installed

**Comment by Sirttas** [comment]
Last update reduced load on network and add the possibility to reduce particle quality either by setting graphics to fast or setting `fastParticleEffects` to true in client config.

Tell me if either of those helps with performance.

**Comment by Sirttas** [comment]
As there is no more discussions on this issue I'm closing it, feel free to open a new one if another problem shows up.
