### ISSUE TITLE
Hello automating infusers is a chore and a half and, they work with various pipes in buggy ways.

### ISSUE THREAD

**Issue by 64thParaDux** [Sirttas/ElementalCraft#26]
**Describe the bug**
While using various mods item bug out disappear sometimes crash it's just sorta unstable sometimes. I know pipes are hard to code so it's not 100% your fault but its more buggy than other similar mods.

**To Reproduce**
1.infuser setup with air element using small containers and basic pipes. a hopper pointing down into a cable and cable into Elemental craft Infuser

**Expected behavior**
like a hopper no back up in pipes and with some it make the pipes break rendering your system useless.

**ModPack**
TNP Limitless 3 1.8.2/1.8.3

**Comment by Sirttas** [comment]
Can you please correct you sentences because I don't understand what you mean.

**Comment by Sirttas** [comment]
As there is no answer after two weeks on this and I can't understand what your problem is I'm closing this issue.
Feel free to open a new one with a corrected description. 
Also if you have a crash it's **imperative** that you add a crash report to your issue.
