### ISSUE TITLE
Essence Infusion into tools to increase the level of enchantment, has no limit...

### ISSUE THREAD

**Issue by Mowmaster** [Sirttas/ElementalCraft#27]
**Describe the bug**
Not a bug, but more like a multi mod interaction that can produce insane levels of an enchant.

**To Reproduce**
1. Normally, say for water essence, you infuse a pick with it, and it gets fortune 1, it wont go above that because of an nbt tag that wont allow it.
2. But some mods add ways to disenchant tools, now we have an enchanted book, and a tool with an nbt tag.
3. Get a new tool, throw the book on it. (There is a number of ways to do this once you exceed the level cap for a vanilla anvil, botania enchanter, or pedestal exp anvil for examples)
4. Automate this process for basically unlimited levels of enchants, there is at some point an infeasible limit, but this automation can be done super quickly since it appears the cost to infuse is a set amount, and not based on the current enchantment level.

**Expected behavior**
Ideally some sort of increasing cost to infuse the enchant by 1 level, this would at least time gate the process and slow down the automation, considering essence seems to be infinite, there is probably no way to get rid of this 'issue' but a way to make it basically infeasible, but not impossible to obtain an insane level should deff be looked into. (or you can just config in a hard cap for the process too)

**ModPack**
ATM6
https://imgur.com/a/E9y2VTH

**Comment by Sirttas** [comment]
Fixed in 1.16.4-2.5.2

**Comment by patrik1123456** [comment]
> Fixed in 1.16.4-2.5.2

so i can no longer get fortune 1k?

**Comment by Sirttas** [comment]
> so i can no longer get fortune 1k?

No

**Comment by patrik1123456** [comment]
> > so i can no longer get fortune 1k?
> 
> No

:(
