### ISSUE TITLE
No visual representation anymore

### ISSUE THREAD

**Issue by davqvist** [Sirttas/ElementalCraft#28]
**Describe the bug**
Since a recent update, everything I craft, be it infusing or binding, I get no visual representation of the crafts anymore. There are no particles, for example making drenched iron works, but when it is done, I still see the Iron Ingot on the Infuser, even after retrieving the Drenched Iron Ingot. The Containers also all show as empty when piping in, etc...
I first thought it is a mod interaction, but even a clean install with basically only Elementalcraft, causes this issue. No Optifine or anything strange added.

**To Reproduce**
1. Spawn in a elemental water source or find one in world
2. Put Extractor and Container under it
3. Place pipe next to container and set to extracting
4. Place another container next to it, fed by the pipe with Infuser on top
5. Place Iron Ingot in Infuser
-> No visual representation on the craft and the second container seems empty.

**Expected behavior**
To get particles and render of items when crafting

**ModPack**
Happens with only Elementalcraft, JEI and The One Probe

Elementalcraft 2.5.2
DpAnvil 1.0.6
Forge 35.1.36
MC 1.16.4

**Comment by Sirttas** [comment]
Yeah this is a synchronization bug introduced in 2.5.2. It will be fix in the upcomming update

**Comment by Sirttas** [comment]
fixed in 1.16.4-2.5.3

**Comment by Sirttas** [comment]
Also this is a great issue description!

**Comment by davqvist** [comment]
Thank you a lot, I tried my best. Shows I have a bit of experience in reporting bugs from the past :P
