### ISSUE TITLE
Adding an item for Creative Mode

### ISSUE THREAD

**Issue by BlackStone5677** [Sirttas/ElementalCraft#29]
I think an Element Switcher item would be a good addition for creative mode and survival mode(Mainly creative), 
What it would do is if you hit it on an element source it switches the element type from water to air to fire to earth to water etc. 
So if someone wants to do creative testing they can do it with ease. 
Another main reason would be that I want to make a pack that uses elementalcraft and I don't want people to explore a lot but exploring would still be encouraged so people won't need to explore to find all element sources(They are allowed to explore still) Instead they'll be given one element source and one element switcher when they spawn and they can use elementalcraft without the need of exploring. 
This item is also useful for skyblock packs as you shouldn't need to explore to get resources.

**Comment by Sirttas** [comment]
I don't rely see how this would add anything to the mod. You should look at the element evaporator it has been created for skyblock packs.
