### ISSUE TITLE
ElementalCraft not Compatible with Advanced Mining Dimension

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Sirttas/ElementalCraft#3]
I'm making a modpack using ElementalCraft. The ores from both mods are not generating within the [Advanced Mining Dimension](https://www.curseforge.com/minecraft/mc-mods/advanced-mining-dimension/files/3061058) as expected. I have posted this issue with henkelmax (dev for mining dimension) as shown [here](https://github.com/henkelmax/advanced-mining-dimension/issues/9). He suggested a datapack, which I have tried without success. It would be nice if your mods could generate ores in the mining dimension.

The pack is not published yet, but here is the latest Twitch/MultiMC install: 
[Paradise in Chaos-0.2.0.zip](https://github.com/Sirttas/ElementalCraft/files/5258354/Paradise.in.Chaos-0.2.0.zip)

Forge: 34.0.9
Minecraft: 1.16.3
elementalcraft-1.16.2-2.2.12

**Comment by Sirttas** [comment]
Ok fixing this bug require two things:
- updating to forge 34.0.2+ making it uncompatible with 1.16.2
- mooving worldgen to datapack instead of java

I'll do the later, but I'll wait before droppint 1.16.2 support as you may understand.

**Comment by ClaudiusMinimus** [comment]
Look forward to seeing the update. Thanks!

**Comment by Sirttas** [comment]
Fixed in 1.16.3-2.3.0
