### ISSUE TITLE
Item Output Retriever seems to get "stuck" when pulling from Ore Purifier

### ISSUE THREAD

**Issue by daAresinger** [Sirttas/ElementalCraft#30]
I have set up a simple ore duplication system. However the purified ore appears to get stuck in the purifier.
Every now and then I have to "jumpstart" the system, by taking out the purified ore and cooking it in a separate furnace.

It appears that the reason for this is because the purifier fills up, while the furnace is working. Once the purifier is full the ore is no longer retrieved. (I assume because there are no events sent by the ore purifier? Assuming you are using a subscriber model)

I am playing ATM6 (the latest version as of 20th Jan 2021)
Screenshot:

![2021-01-23_23 50 04](https://user-images.githubusercontent.com/24697123/105616385-c5ed9b80-5dd6-11eb-9e92-ddc9f300f535.png)

**Comment by Sirttas** [comment]
The instrument output retriever is only 'activated' on craft completion fil your ore purifier is clogged up it wont craft and therefore wont output, I will fix it for nex patch.

**Comment by Sirttas** [comment]
Fixed in 2.5.6
