### ISSUE TITLE
Crash from Binder

### ISSUE THREAD

**Issue by lynaevm** [Sirttas/ElementalCraft#31]
**Describe the bug**
Fatal crash on both server and single player as soon as player attempts to use the Binder for the first time to make the gold alloy. As soon as all 4 items are placed and particles start, game crashes.

**ModPack**
TNP Limitless 3, version 3.19.1a

Elementalcraft version 2.5.4

crashlog: https://pastebin.com/DbKt4mqu

**Comment by Sirttas** [comment]
This has been fixed in 2.5.5 please update.
