### ISSUE TITLE
Source render under clouds

### ISSUE THREAD

**Issue by ghost** [Sirttas/ElementalCraft#32]
I have read on reddit (from a few months ago) that you are aware of the way elemental sources are rendered behind clouds and how you haven't found a solution to it yet. I also have seen this issue being present on many others mods (example: astral sorcery rays, botania's mana pool particles, etc).
The thing I wanted to inform, that you may not know/have noticed yet, is that the newish dark magic mod Eidolon (https://www.curseforge.com/minecraft/mc-mods/eidolon) has some very visually similar semi transparent animated sprites that do not suffer from that ordering bug (its ritual "notification").
I do not have the skills to check if the way elucent implemented could show you a solution, so I decided to comment here since Eidolon source is also on github (https://github.com/elucent/eidolon).
Eidolon has one short coming tho, as its sprites does not render on minecraft's fabulous mode.
It may be worth a check, if you by any chance consider this inapplicable please close this issue. 
Thank you for your time.

![Screenshot from 2021-01-25 21-29-30](https://user-images.githubusercontent.com/64246231/105783139-8cdb3580-5f54-11eb-9403-35b3e208bc88.png)

**Comment by Sirttas** [comment]
Eidolon 's rituals doesn't use particles like EC does. I'll keep this issue open, it will be the main issue for this bug.

**Comment by Sirttas** [comment]
issues form mojang bug tracker:

https://bugs.mojang.com/browse/MC-9553
https://bugs.mojang.com/browse/MC-167532
https://bugs.mojang.com/browse/MC-170695
https://bugs.mojang.com/browse/MC-188151
https://bugs.mojang.com/browse/MC-233704

**Comment by Sirttas** [comment]
Fixed in 1.19-5.0.0
