### ISSUE TITLE
absurdly high network bandwidth usage

### ISSUE THREAD

**Issue by MaxMatti** [Sirttas/ElementalCraft#33]
tl;dr: This mod causes my bandwidth usage to go up to 3MiB/s which exceeds my internet speeds and thus disconnects me from my server after about a minute due to my "poor connection".

Mod version: 2.5.1 (iirc this should be the one where the bandwidth usage is [supposed to be less](
https://github.com/Sirttas/ElementalCraft/issues/25#issuecomment-759717712)?)
Modpack: ATM6 version 1.4.1

See detailed description here:
https://github.com/AllTheMods/ATM-6/issues/949

**Comment by Sirttas** [comment]
this is strange because I literally removed so updates calls, I'm looking into it.

**Comment by Sirttas** [comment]
It should be much better in the last version (2.5.6).

**Comment by MaxMatti** [comment]
Seems to be fixed, thank you very much! I was able to just drop in the new jarfiles and everything worked fine.

**Comment by Sirttas** [comment]
Good. Out of curiosity can you run your benchmark again ?

**Comment by MaxMatti** [comment]
Of course:

again all numbers in KiB
| location | download | upload |
| ---- | ---- | ---- |
| ocean | 50-80 | 12-30 |
| plains | 50-80 | 12-30 |
| base | 400-700 | 90-130 |

not sure why our base uses even less bandwidth than in the previous benchmark in the "after cleanup" run. Most likely I forgot some place during the cleanup where somebody had built some contraption. Again thank you very much for the fast reply and fix!

**Comment by Sirttas** [comment]
No problem. This is the kind of problems that needs immediate attention.
