### ISSUE TITLE
 Mahou Tsukai Infusion

### ISSUE THREAD

**Issue by Rumaan3012** [Sirttas/ElementalCraft#35]
Not sure if this is an issue with the Mahou Tsukai mod or your side, but the Morgan cannot receive the Air Infusion. Tested a normal blade right after and the infusion worked on that one, so I have the correct setup.

**Comment by Sirttas** [comment]
Elemental craft use tags for infusion (`elementalcraft:infusable/sword`, `elementalcraft:infusable/axe`, `elementalcraft:infusable/pickaxe` etc.) these  tags contains the forge tags for corresponding tools (`forge:sword`, `forge:axe`, `forge:pickaxe` etc.). Either add Mahou Tsukai to the corresponding tag on your pack (or ask the pack creator to do it) or ask Mahou Tsukai to put it's tool to forge tags.

**Comment by Rumaan3012** [comment]
Thanks for clarifying! I'll bring it to the right person then.
