### ISSUE TITLE
cannot be add more output in recipe

### ISSUE THREAD

**Issue by AlleCraft-alterego** [Sirttas/ElementalCraft#36]
cannot be add more output in this recipe:

-binding
-pure infusion
-gem crystallizer
-element infuser
-rune inscription

**Comment by Sirttas** [comment]
Do you mean having multiple output for one recipe or adding new recipe ?

**Comment by AlleCraft-alterego** [comment]
sorry, multiple output

**Comment by Sirttas** [comment]
Fixed in 2.5.8
