### ISSUE TITLE
Source blocks cause vine blocks to crash when vine blocks are above source blocks due to forge inconsistency

### ISSUE THREAD

**Issue by Commoble** [Sirttas/ElementalCraft#4]
Forge currently has an issue where the vanilla version of blockstate.isAir() and the forge version of blockstate.isAir(world, pos) can differ on certain blocks.

Forge also currently has an issue where vine blocks are improperly patched, causing them to crash when above blocks where isAir() is false, but isAir(world, pos) is true. This primarily occurs on blocks whose material is Material.AIR, but whose Block.Properties does not call .setAir() when defining the block instance.

https://github.com/MinecraftForge/MinecraftForge/issues/7406

The elementalcraft:source block is affected by this issue, as seen in this crash report:

https://gist.github.com/Commoble/e675e3ba0fa8366a6200c4eefd184f14

However, the crash can be averted on elementalcraft's end by calling .setAir() on the source block's Block.Properties.

**Comment by Sirttas** [comment]
Fixed in 1.15.2-1.2.2 and 1.16.3-2.3.4
