### ISSUE TITLE
Growth Shrine not working on mystical agriculture

### ISSUE THREAD

**Issue by elementalistic** [Sirttas/ElementalCraft#41]
Having a Growth shrine inline with minecraft farmland and/or the Inferium farmland does not speed up the growth of Inferium Seeds.  Tested the same setup with wheat and it is working.

**ModPack**
ATM6 v1.5.2

**Comment by Sirttas** [comment]
Have you tried with a boneless growth shrine upgrade ?

**Comment by elementalistic** [comment]
I'd only just unlocked the growth shrine and hadn't even noticed that upgrade.  It's working with it.

Perhaps a note on the shrine page in the book about the upgrade?

**Comment by Sirttas** [comment]
> Perhaps a note on the shrine page in the book about the upgrade?

I just thought about it I added it to next version.
