### ISSUE TITLE
Growth shrine stops Lilypad of Fertility from working

### ISSUE THREAD

**Issue by elementalistic** [Sirttas/ElementalCraft#42]
Having the shrine inline with the lilypad of fertility, so 1 above the farmland, causes the particle effects to generate fast on the lilypad  but the growth effect from the lilypad stops working entirely, or at least didn't trigger over a few minutes.

**ModPack**
ATM6 v1.5.2

**Comment by elementalistic** [comment]
More playing with this, sometimes the lilypad keeps working as normal.   Sometimes it stops working entirely.  Sometimes there is a large delay for the effect of the lilypad.  It doesn't seem to matter which order the lilypad and the shrine is put down in.

**Comment by Sirttas** [comment]
It doesn't seem to be a problem with the growth shrine as I just had a lilypad alone and it wasn't working.

**Comment by Sirttas** [comment]
I tested a bit more and I really think it is an issue with the lilypad itself, I would recommend opening an issue to the correct project.
