### ISSUE TITLE
Fus/Wii runes have swapped recipes

### ISSUE THREAD

**Issue by truenachtara** [Sirttas/ElementalCraft#43]
**Describe the bug**
Fus and Wii runes have the wrong recipes, they should be switched.
![image](https://user-images.githubusercontent.com/16340367/108587992-74282a80-731c-11eb-9f62-1bd4e67c76e0.png)
![image](https://user-images.githubusercontent.com/16340367/108588003-84d8a080-731c-11eb-81cd-f1acde33e383.png)

**Possible fix**
Simply switch the outputs

**Comment by Sirttas** [comment]
fixed in 2.5.12
