### ISSUE TITLE
Spells break in spite of full Element Holders

### ISSUE THREAD

**Issue by ThinkingQuill** [Sirttas/ElementalCraft#45]
**Describe the bug**
Whenever I cast any spell using either a spell scroll OR the focus, the spell is destroyed in spite of the fact that i have all four types of element holder, all of which are full.

**To Reproduce**
1. Build or Acquire a spell scroll (optional put it in a focus with the anvil)
2. Build All four types of Element Holder
3. Fill all element holders using element sources
4. attempt to cast a spell

**Expected behavior**
As described by the book, videos, and other posts that I've seen, the spell should take an amount from the element holder and remain in my inventory/focus

**ModPack**
Either a known pack (ex: ATM6) or a Twitch/MultiMC export
ATM6

**Comment by Sirttas** [comment]
It has been fixed in recent versions, please update elemental craft.
