### ISSUE TITLE
improved element binder crashing

### ISSUE THREAD

**Issue by boboop143** [Sirttas/ElementalCraft#46]
**issue: every time I place the improved element binder on a tank my game crashes and I need to load a backup of my world to play it again**

**Modpack: ATM6**

[crash-2021-03-21_09.22.11-server.txt](https://github.com/Sirttas/ElementalCraft/files/6177037/crash-2021-03-21_09.22.11-server.txt)

**Comment by Sirttas** [comment]
Don't use it for now until I fix it.

**Comment by Sirttas** [comment]
fixed in 2.6.4
