### ISSUE TITLE
Cant connect to a server with the new update (And starting it takes longer than it should)

### ISSUE THREAD

**Issue by sirben99** [Sirttas/ElementalCraft#47]
Describe the bug
Hey!

It seems that i cant connect to the server with the newest elemantalcraft. This is the error: 
![image](https://user-images.githubusercontent.com/32977052/113323652-e1b57680-931e-11eb-9a09-7364ece98408.png)

To Reproduce
1. Update modpack
2. Try to connect to server
3. Get the error

Expected behavior
I should be able to connect to the server no problem

ModPack
Custom made, private on Technic launcher for easy updates.

Other information:
Minecraft: 1.16.5
Forge: 36.1.0
ElementalCraft: 1.16.5-2.6.6.jar
JustEnoughItems: 1.16.5-7.6.1.75.jar
Patchouli: 1.16.4-50.jar
Other mods: Tested with and without. More info on without other mods below

IMPORTNAT: I noticed that with the newest elemental craft update, i cant connect to a server at all. I tested the mod only with the dependencies and nothing else (No extra mods). The world creation also takes wayyy more time than usual. When removing ElementalCraft, server starts way quicker and i can connect without any errors. So its defenatly something wrong with ElementalCraft.

My latest.log (Without other mods): 
[latest.log](https://github.com/Sirttas/ElementalCraft/files/6244994/latest.log)

Server latest.log (Without other mods):  
[latest.log](https://github.com/Sirttas/ElementalCraft/files/6245001/latest.log)

My latest.log (With other mods):
[latest.log](https://github.com/Sirttas/ElementalCraft/files/6245019/latest.log)

Server latest.log (With other mods):
[logs_latest.log](https://github.com/Sirttas/ElementalCraft/files/6245021/logs_latest.log)

Sorry for the mess of a issue but i wanted to give as much information as i could. I hope this helps at least a little bit!

Ben

**Comment by Sirttas** [comment]
Fixed in 2.6.7
