### ISSUE TITLE
[Suggestion] Project MMO Compatibility

### ISSUE THREAD

**Issue by faeldray** [Sirttas/ElementalCraft#49]
[Project MMO](https://www.curseforge.com/minecraft/mc-mods/project-mmo) is a mod where you can level up different skills (agility, combat, farming, cooking, smithing, etc.) and you get better and better perks as you level.

So specifically, it would be great if ElementalCraft furnaces gave smithing/cooking XP depending on what it's processing. Also, the perk of the smithing and cooking skills are that you get an increased chance of extra outputs as you level. So it would be great if EC furnaces also supported those.

There is an API listed [about 3/4 of the way down this page](https://harmonised7.github.io/minecraft/pmmo/Features.html) although I'm not sure how helpful it could be to you.

**Comment by Sirttas** [comment]
I don't think I'll get the time to do it. Sorry.
