### ISSUE TITLE
Server crash - elementalcraft-1.16.3-2.3.4

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [Sirttas/ElementalCraft#5]
**Describe the bug**
A player mentioned he casted some kind of scroll.

**To Reproduce**
A player mentioned he casted some kind of scroll.

**Expected behavior**
Not to crash the entire server

**Screenshots**
![image](https://user-images.githubusercontent.com/7256303/95674715-526ea800-0bb2-11eb-87aa-a33e6ec65860.png)

**Additional context**
ElementalCraft: elementalcraft-1.16.3-2.3.4.jar
Modpack: All the Mods 6-1.1.2

**Comment by Sirttas** [comment]
fixed in 1.15.2-1.2.3 and 1.16.3-2.3.5
