### ISSUE TITLE
Reservoirs don't show element levels.

### ISSUE THREAD

**Issue by Furious1964** [Sirttas/ElementalCraft#51]
**Describe the bug**
There's no indication of the level of how much element I have in the reservoirs like in the containers.

**To Reproduce**
1. Place container and reservoir down with same element.
2. Hover cursor on them.
3. Container shows level of element but not the reservoir.

**Expected behavior**
Expected to see how much was inside it.

**ModPack**
ATM6 1.6.2, Elementalcraft Version 2.6.9

**Comment by Sirttas** [comment]
fixed in 2.7.0
