### ISSUE TITLE
Items not craftible in crafting station from Tinker's Construct

### ISSUE THREAD

**Issue by Diversion98** [Sirttas/ElementalCraft#52]
I can craft items from elemental craft in a workbench (vanilla and the fastworkbench mod).
I can't craft items from elemental craft in the crafting station from Tinker's Construct. (recently added on CurseForge).
Other mods work perfectly with the crafting station from Tinker's Construct.

1. place a Crafting Station from Tinker's Construct
2. try to craft anything from Elemental Craft
3. It'll show the product but you can't have it.
    It might glitch and show it in your inventory but once you open the crafting station again, your item is gone and the items needed for the product is back in the Crafting Station

**Expected behavior**
Items from Elemental Craft should be craftable when using Tinker's Construct.

**ModPack**
https://www.curseforge.com/minecraft/modpacks/mhg

**Comment by Sirttas** [comment]
This is strange as recipes from elemental craft are not different than vanillas or any other mod's. It may be a bug in TC3.

**Comment by Diversion98** [comment]
Ill make an issue on their github page as well.

Thought i post it here because every other mod (290 in total) does work so.

https://github.com/SlimeKnights/TinkersConstruct/issues/4446

**Comment by Sirttas** [comment]
I'm looking into it, maybe I'm doing something wrong.

**Comment by Sirttas** [comment]
works fine with only the two mods its a problem on the pack.
