### ISSUE TITLE
Can't craft Swift Alloy

### ISSUE THREAD

**Issue by noncom** [Sirttas/ElementalCraft#55]
**Describe the bug**
Can't craft Swift Alloy: I put all the items on the Element Binder but nothing happens:

![37e98cd3d0](https://user-images.githubusercontent.com/2920144/132037949-47517064-931a-456b-b36d-d9157ee69095.jpg)

**To Reproduce**
Try crafting Swift Alloy.

**Expected behavior**
Crafting Swift Alloy works.

**ModPack**
Limitless 4 version 0.6.0 (includes Elemental Craft 1.17.1-3.1.2), I'm playing on the official server.

**Comment by Sirttas** [comment]
The recipe changes in 1.17.1, add copper before Redstone.

**Comment by noncom** [comment]
Oh! Thanks! I see now it works! :) I'll look at the recipe JSONs first the next time.

**Comment by Sirttas** [comment]
JEI interaction is comming back next week
