### ISSUE TITLE
Element Containers Show Multiple Level Indicators

### ISSUE THREAD

**Issue by Ocraftyone** [Sirttas/ElementalCraft#56]
**Describe the bug**
Exactly what the title says: all of the element containers show two level indicators on the screen
**To Reproduce**
Look at an element container in-world

**Expected behavior**
Show only one indicator by crosshair

**ModPack**
ATM7 1.17.1

![image](https://user-images.githubusercontent.com/24759591/134142669-4b9c45d5-3ebe-4975-8cc9-298fc0f77e3b.png)
![image](https://user-images.githubusercontent.com/24759591/134142772-abcc07e6-d187-4644-b534-50ebfd8c2a97.png)

**Comment by Sirttas** [comment]
I rework the gauge code a bit. I thik its fixed but I'm unable to reproduce it. Please open a new issue if the problem persist.
