### ISSUE TITLE
Silent Gear material categories missing

### ISSUE THREAD

**Issue by SilentChaos512** [Sirttas/ElementalCraft#57]
Hey, thanks for supporting Silent Gear! Had a small issue pointed out to me on my Discord server.

**Describe the bug**

Silent Gear materials are currently missing categories, which makes them impossible to use in the compound-making blocks like the metal alloyer. This can be fixed be adding the `categories` array under the `availability` object in the JSON file ([example](https://github.com/SilentChaos512/Silent-Gear/blob/1.17.x/src/generated/resources/data/silentgear/silentgear_materials/iron.json#L4-L6)). I suggest "metal" for ingots. Other common categories can be seen [here](https://github.com/SilentChaos512/Silent-Gear/blob/1.17.x/src/main/java/net/silentchaos512/gear/gear/material/MaterialCategories.java#L10).

**To Reproduce**

1. Place ingots in the metal alloyer
2. Nothing happens

**Expected behavior**

Materials to be categorized correctly.

**ModPack**

N/A

**Comment by Sirttas** [comment]
Hi thanks for the bug report. Is this a problem in 1.16 to or only 1.17?

**Comment by SilentChaos512** [comment]
Both. Categories were added a while back.

**Comment by Sirttas** [comment]
OK. Thanks you. I will fix it soon.

**Comment by Sirttas** [comment]
fixed in 2.7.12 (1.16.5). I keep this opened until I merged it to 1.17.

**Comment by Sirttas** [comment]
fixed in 3.2.0 (1.17.1).
