### ISSUE TITLE
[1.16.5] Pipe cover frames not rendering properly

### ISSUE THREAD

**Issue by dan96kid** [Sirttas/ElementalCraft#58]
**Describe the bug**
Pipe cover frames that have been right clicked with a block turn invisible if there's no item in your hand.
![image](https://user-images.githubusercontent.com/14021093/136684103-9add87d2-b97e-45ee-a5c5-ae7d4be8ba8b.png)

**To Reproduce**
1. Place a pipe cover frame
2. Right-click it with any solid block
3. Select an empty spot on your hotbar

**Expected behavior**
Pipe cover frame is supposed to render as the block that it was right-clicked with when your selected hotbar slot is empty.
Screenshot showing what the pipe cover frame is supposed to look like even if the selected hotbar slot is empty. (Using a vanilla stone block as an example)
![image](https://user-images.githubusercontent.com/14021093/136684148-36efd59b-55bb-4e57-9fa7-616736ce7f50.png)

**ModPack**
All The Mods 6

**Comment by Sirttas** [comment]
Hi this is the normal behaviour.
