### ISSUE TITLE
CraftTweaker support?

### ISSUE THREAD

**Issue by SureenInk** [Sirttas/ElementalCraft#6]
I am enjoying this mod. I would like to add it to my modpack, but if I did, I'd like to see if it can have CraftTweaker support for custom recipes and such like that? Would this be possible?

**Comment by Sirttas** [comment]
All the recipes can be changed in data pack.

**Comment by Sirttas** [comment]
Crafttweaker can now handle json recipes: https://www.reddit.com/r/feedthebeast/comments/kyay1t/crafttweaker_andor_kubejs/gjh379v?utm_medium=android_app&utm_source=share&context=3
