### ISSUE TITLE
Server disconnection causing crash

### ISSUE THREAD

**Issue by jeremiahwinsley** [Sirttas/ElementalCraft#62]
**Describe the bug**
A bad packet sent from a server (which would normally disconnect and go back the menu) now crashes and blames Elementalcraft.

This seems to be caused by the removal of the shortcircuit operator in this change: https://github.com/Sirttas/ElementalCraft/commit/bbf52f0c9fed4871f08dd2e491383c6469deeb82#diff-d92385348960dd9ae465736ec4d19732586086af4f02cace2bb732e2fa359845R126

Crash log here: https://gist.github.com/jeremiahwinsley/3be500dc663d6fd2aa95432c20272c21

**To Reproduce**
This only happens when a bad packet is sent, one way of triggering that:
1. install Curious Elytra in ATM6 1.8.6
2. wear a Silent Gear elytra in the Curios back slot.
3. Close the client completely, then restart it and try to connect to the server.

**ModPack**
ATM6 1.8.6

**Comment by Sirttas** [comment]
Sould be fixed in 2.7.13
