### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by TheNimbleNinja** [Sirttas/ElementalCraft#64]
**Describe the bug**

**To Reproduce**
https://gist.github.com/TheNimbleNinja/54f544f9c47f80727c14a5b4c1c1d20b

**Expected behavior**

**ModPack**
Either a known pack (ex: ATM6) or a Twitch/MultiMC export

**Comment by Sirttas** [comment]
please fill all the fields of the issue... I don't know what happened, you just gave me a crash report where I have one mixin without even knowing if EC is the cause or no.

**Comment by TheNimbleNinja** [comment]
i have no idea wat caused this to crash
