### ISSUE TITLE
[1.16.5 Bug][Mod interaction] Presence of Undergarden mod makes all ore purifying produce Undergarden pure ore chunks

### ISSUE THREAD

**Issue by LuciusV** [Sirttas/ElementalCraft#65]
ElementalCraft 1.16.5 -2.7.13
Forge 36.2.8

**Describe the bug**
Undergarden mod adds its own iron, gold etc ore
Ore purification using common ores produce  Undergarden pure ore chunks by default instead of common ones

**To Reproduce**
With Undergarden https://www.curseforge.com/minecraft/mc-mods/the-undergarden mod installed, put iron ore into ore purifier
Got undergarden pure iron ore 

**Expected behavior**
Expect to get pure iron ore chunk

**ModPack**
No modpack

**Comment by Sirttas** [comment]
does these ore smelt to iron, gold etc.? Ores that are smelt to the same ingot are grouped , the problem seems to be that they are grouped to the wrong ore.

**Comment by LuciusV** [comment]
They do smelt and are processed normally by another mods like Mekanism, 
but its better if output for vanilla ore would be vanilla ore chunk :)

**Comment by Sirttas** [comment]
This is a minor inconvenience and is no longer present in 1.17 onward. So I'm closing this issue.
