### ISSUE TITLE
[1.17] Crystallizers only output Crude Air, Water, and Fire shards, but only Pristine Earth Gems

### ISSUE THREAD

**Issue by BiFrossGames** [Sirttas/ElementalCraft#67]
Steps to repeat: Literally just try to make crystals using a diamond first, then the leftover shards with the attuned Crystals

**Comment by SkyTheCodeMaster** [comment]
Game version: 1.17.1
Mod version: elementalcraft-1.17.1-3.2.0.jar
Multiplayer? Yes

**Comment by Sirttas** [comment]
Fixed in 4.1.4
