### ISSUE TITLE
NPE that seems to be from Reliquary, but they think may be from you

### ISSUE THREAD

**Issue by Letoric** [Sirttas/ElementalCraft#7]
Can you look at this, and perhaps engage with them to solve regardless of who owns it?

https://github.com/P3pp3rF1y/Reliquary/issues/462

Thank you

**Comment by Sirttas** [comment]
This entity is part of a WIP feature rthat is not called anywhere. other mods seems to sumon it for unknown reason. If you can remove it in config I would recommand to do so.

**Comment by Sirttas** [comment]
fixed in 2.3.15
