### ISSUE TITLE
Sources not spawning 

### ISSUE THREAD

**Issue by LasairNova** [Sirttas/ElementalCraft#70]
I am currently on 1.18.1, all recipes are present and I get shards form drops, but source orbs have not spawned in my world.

**Comment by Sirttas** [comment]
What mod version are you on?

**Comment by LasairNova** [comment]
I am running version 1.18.1-4.1.5

I am running other mods, but no world generation mods

**Comment by remclave** [comment]
Sources for version 1.18.1-4.1.5 DO spawn but I didn't find one until I explored over 6 Km from my established base. Check near genned structures, like illager (pillager?) towers.

**Comment by LasairNova** [comment]
Is there anyway to increase the spawn rate?

**Comment by Sirttas** [comment]
Fixed in 4.1.6
