### ISSUE TITLE
Spell desk does not work like manual says (1.16.5, elementalcraft-1.16.5-2.7.13.jar)

### ISSUE THREAD

**Issue by darchitectlp** [Sirttas/ElementalCraft#71]
**Describe the bug**
Manual says to right click with scroll and stack of infused crystal; instead a GUI opens

**To Reproduce**
Right click on spell desk, GUI opens. No clear indicator of how to craft new spells.

**Expected behavior**
What it says in the manual.

**ModPack**
Either a known pack (ex: ATM6) or a Twitch/MultiMC export
Permafrost

**Comment by Sirttas** [comment]
Look for the recipes in JEI

**Comment by darchitectlp** [comment]
Yup, figured that out. May want to update your book (and spell check it, when you get a chance). Thanks for a fun mod!

**Comment by Sirttas** [comment]
fix in 4.1.7 (1.18)
