### ISSUE TITLE
Crash on World Load

### ISSUE THREAD

**Issue by oliverrook** [Sirttas/ElementalCraft#72]
**Describe the bug**
Crash on world Load. World finishes generating, but the moment it fully loads it crashes. I believe it is a mod compatibility issue, but I am unsure what is causing it. This occurred after updating Elemental Craft to version 2.7.14 for version 1.16.5 though it was from version 2.7.12. This was the only mod updated. The pack loaded into worlds without issue before. I have yet to see if reverting to 2.7.12 fixes the issue.

**To Reproduce**
Unsure, however I have noticed it throws an error referencing other mods most of the time, however disabling these mods simply replaces the error with a similar one referencing a different mod. It will also error on attempting to verify datapacks if they are attempted to be changed.

**Expected behavior**
Loading into a world.

**ModPack**
A heavily modified version of All The Mods 6.

Crash log: https://pastebin.com/9YJvzMDX

I do apologize if it is not actually this mod causing the problem, but I am unsure what else it could be, and loading the mod pack takes 15-20 minutes every load, and I do not have the time to go through the entire list of 400 mods to confirm this 100%. I have done so in the past with other mods and it has taken most of my day.

**Comment by Sirttas** [comment]
> Registry entry not present: create:diving_helmet

Looks like something with create.
