### ISSUE TITLE
Elementopedia Entry Bugs

### ISSUE THREAD

**Issue by operatoroperon** [Sirttas/ElementalCraft#74]
The Elementopedia shows "block.elemental.craft.tank_small" in both the title and text of the basic storage tank entry, and nothing else. Additionally, it's not giving credit for reading the section on pipes.

**Mods Involved**
hexerei-0.1.14.jar, EnchantmentDescriptions-Forge-1.18.1-9.0.11.jar, Companion-1.18-forge-1.1.1.jar, biggerreactors-1.18.1-0.6.0-beta.0.2.jar, RootsClassic-1.18.1-1.1.19.jar, ImmersiveEngineering-1.18.1-7.1.0-145.jar, verdure-1.18.1-1.0.4.jar, Jade-1.18-4.1.2.jar, flatbedrock-1.4.1-build.8+mc1.18.1.jar, jei-1.18.1-9.2.1.69.jar, ThisRocks-1.18.1-1.0.0.jar, dpanvil-1.18.1-3.2.0.jar, Patchouli-1.18.1-65.jar, elementalcraft-1.18.1-4.1.7.jar, moreconcrete-1.2.1-1.18.1.jar, journeymap-1.18.1-5.8.0beta15.jar, Placebo-1.18.1-6.1.0.jar, AutoRegLib-1.7-53.jar, StorageDrawers-1.18.1-10.1.1.jar, NaturesCompass-1.18.1-1.9.4-forge.jar, FruitTrees-1.18.1-forge-4.1.3.jar, primalmagick-2.0.5.jar, Decorative+Blocks-forge-1.18.1-2.0.4.jar, Regrowth-1.18.1-1.39.0.26.jar, phosphophyllite-1.18.1-0.6.0-beta.0.1.jar, snowundertrees-1.18.1-1.2.jar, guardvillagers-1.18.1.4.0.jar, twigs-1.1.4-forge.jar, quartz-1.18.1-0.0.0-beta.0.1.jar, NaturesAura-35.5.jar, Apotheosis-1.18.1-5.3.2.jar, furniture-7.0.0-pre28-1.18.1.jar, azalea-FORGE-3.1.1.jar, architectury-3.6.17.jar, Floral-Flair-1.18.1-1.3.2.jar, SnowRealMagic-1.18-forge-3.2.2.jar, Kiwi-1.18-forge-5.2.3.jar, productivebees-1.18.1-0.8.0.7.jar, light-overlay-6.0.4-forge.jar, blueprint-1.18.1-5.1.1.jar, cloth-config-6.2.57-forge.jar, forge-1.18.1-39.0.76-universal.jar, Quark-3.1-336.jar, Aquaculture-1.18.1-2.3.3.jar, ironchest-1.18-13.0.7.jar, mcw-lights-1.0.2-mc1.18.1.jar

Thank you!

**Comment by Sirttas** [comment]
Fixed in 4.3.2
