### ISSUE TITLE
ElementalCraft not working with Mystical Agriculture

### ISSUE THREAD

**Issue by ritapia** [Sirttas/ElementalCraft#75]
The growth shrine with a boneless growth shrine upgrade doesn't work with any mystical agriculture seeds. Works on non-mystical agriculture seeds

**Forge Version:** 36.2.26

**Mods Installed**: 

Cucumber-1.16.5-4.1.12
dpanvil-1.16.5-1.2.3
elementalcraft-1.16.5-2.7.14
MysticalAgradditions-1.16.5-4.2.4
MysticalAgriculture-1.16.5-4.2.6

**Log:** [latest.log](https://github.com/Sirttas/ElementalCraft/files/8239293/latest.log)

**Error Sample**: 

[Worker-Main-8/ERROR] [dpanvil/]: Error while making field:  BONELESS_GROWTH accesible
java.lang.NoSuchFieldException: modifiers

**Comment by ritapia** [comment]
Just tried using the Harvester with a planter upgrade and that also didn't work. It wouldn't re-plant mystical agriculture seeds or non-mystical agriculture seeds. I think the upgrades for all the shrines are bugged.

**Comment by Sirttas** [comment]
One feature break from java 12 onward. I'll be fixing it once modmave is back online.
