### ISSUE TITLE
question - Mekanism pure ore chunk proccesing

### ISSUE THREAD

**Issue by edotenseilove** [Sirttas/ElementalCraft#78]
Hello,

Great mod. I quite enjoyed playing Elemental Craft alongside mekanism mod on previous version of MC and since mekanism for 1.18.2 finally came out I would like to ask if there will be an inbuilt configurable pure ore chunk mekanism proccesing for 1.18.2 version of Elemental craft.

Have a great day.

**Comment by Sirttas** [comment]
Yes! I added back mekanism interaction, I still need tot test it though.

**Comment by edotenseilove** [comment]
Thank you.
