### ISSUE TITLE
issue on curseforge that will always install and enable JEI!

### ISSUE THREAD

**Issue by VirtualGaming1** [Sirttas/ElementalCraft#80]
**Describe the bug**
ON CURSEFORGE
It requires JEI according curseforge setting. which me it will always install JEI or if you try to disable JEI it will this mode and same as trying enable this while JEI is disable, it will re enable JEI.

**Expected behavior**
IT SHOULD NOT INSTALL OR RE-ENABLE JEI

**Comment by Sirttas** [comment]
Elemental Craft uses some code from JEI for some features. That's why JEI is labeled as required.

**Comment by VirtualGaming1** [comment]
well i think it should be optional because there are other mods that use JEI coding as well and they dont install JEI but still dose a bit of funcky stuff when disabling JEI.

Main question is can this run without JEI?

**Comment by Sirttas** [comment]
It does run without it.

**Comment by VirtualGaming1** [comment]
so there must be a way that you can set it where it dose not install with this mod because other mods dose that. but when JEI dose get disabled they will get disable but can re-enabling without re-enabling JEI. right now I do have an issue with JEI that is connecting to server and right now I am using REI. and I can not trust this mod in my modpack because I would think that JEI will be installed right away on other player that is installing my modpack.

**Comment by Sirttas** [comment]
I changed jei as optional for all future releases.

**Comment by VirtualGaming1** [comment]
> I changed jei as optional for all future releases.

Thanks!
