### ISSUE TITLE
luck rune bonus on air mill grindstone is not applied if items from it are extracted at a very high speed 

### ISSUE THREAD

**Issue by edotenseilove** [Sirttas/ElementalCraft#83]
**Describe the bug**
Not sure if luck rune bonus on air mill grindstone proccesing is applied when items are being extracted at high speed.

When I pick proccesed items manualy or extract them at a very low speed I sometimes get additional items but if I use for example pipez item pipes for extraction with for example netherite upgrade I always get the same default number of items I am supposed to get without luck bonus.  

**Expected behavior**
Luck bonus should be applied regardless of the extraction speed.

**Comment by Sirttas** [comment]
what version/pack are you on ?

**Comment by Sirttas** [comment]
Also you can use an instrument output retriever to put the result in a chest, and pipe from here.

**Comment by edotenseilove** [comment]
I am playing with version 4.3.6. for 1.18.2

**Comment by edotenseilove** [comment]
I am really sorry but even with instrument output retriever luck is not applied. I processed several stacks of items but without any additional outputs.

**Comment by Sirttas** [comment]
Thanks for the bug report. It gave me the orotundity to revisit luck. I had fix it for the next version, but be aware that moving on recipes from mekanism wont be affected by luck (it could be used to duplicate ingots).

I'm closing this once next release is available as I still have a few things to work on.

**Comment by edotenseilove** [comment]
Okay thanks for great work

**Comment by Sirttas** [comment]
fixed in 4.4.0
