### ISSUE TITLE
Held item crashing.

### ISSUE THREAD

**Issue by ShadowzOfTheDark** [Sirttas/ElementalCraft#85]
**Describe the bug**
Game crashes when holding a tile entity in your hand.

**To Reproduce**
- Place down elemental container in the world with element of any type in it. (I used a creative one in this case)
- Possibly hook it up to something, in this case it was a growth shrine with full acceleration it was connected to.
- Take any item that is normally a tile entity block and hold in your hand, this will crash your game.
   * I've had this happen with bonsai tree pots and rf tools builder thus far.

**Expected behavior**
Game will not crash when holding a tile entity in your hand.

**ModPack**
ATM 7 (0.4.3)
Forge 40.1.20

**The Crash:**
[crash-2022-05-29_13.01.16-client.txt](https://github.com/Sirttas/ElementalCraft/files/8793972/crash-2022-05-29_13.01.16-client.txt)

**Comment by Sirttas** [comment]
fixed in 4.4.3
