### ISSUE TITLE
Crash when breaking pipe frame disguised as Create's framed glass

### ISSUE THREAD

**Issue by sme23** [Sirttas/ElementalCraft#86]
**Describe the bug**
When breaking a pipe with a frame attached disguised as Framed Glass from Create, the game will crash immediately.

**To Reproduce**
1. Place a pipe (I used an improved pipe when testing).
2. Place a frame on the pipe.
3. Place a Framed Glass block in the frame.
4. In survival mode, break the block with a pickaxe.
5. Game crashes.

**Expected behavior**
No crash, block to drop framed glass & pipe (seems that even with other blocks the frame never drops? dunno if that's also a bug or not)

**ModPack**
[test.zip](https://github.com/Sirttas/ElementalCraft/files/8819837/test.zip)
(This is just ElementalCraft and its dependencies, Create and its dependencies, and JEI)
Here's the crash report as well https://pastebin.com/nVEy32gr

Fairly sure this has something to do with connected textures but don't know who would be handling something incorrectly, so I'm cross-posting this here and in Create's issue tracker https://github.com/Creators-of-Create/Create/issues/3086

**Comment by Sirttas** [comment]
fixed in 4.4.4
