### ISSUE TITLE
Pure Infuser Crash

### ISSUE THREAD

**Issue by El-Basurero** [Sirttas/ElementalCraft#87]
**Describe the bug**
I believe the pure infuser caused the crash documented in the attached crash report. 

> Name: elementalcraft:container // sirttas.elementalcraft.block.container.ElementContainerBlockEntity
	Block: Block{elementalcraft:container}[east=false,north=true,south=false,west=false]
	Block location: World: (485,119,-4146), Section: (at 5,7,14 in 30,7,-260; chunk contains blocks 480,-64,-4160 to 495,319,-4145), Region: (0,-9; contains chunks 0,-288 to 31,-257, blocks 0,-64,-4608 to 511,319,-4097)
	Block: Block{elementalcraft:container}[east=false,north=true,south=false,west=false]
	Block location: World: (485,119,-4146), Section: (at 5,7,14 in 30,7,-260; chunk contains blocks 480,-64,-4160 to 495,319,-4145), Region: (0,-9; contains chunks 0,-288 to 31,-257, blocks 0,-64,-4608 to 511,319,-4097)

The pure infuser is the block at (485,119,-4146). The crash occurred when I came into view of the pure infuser while flying using a jetpack from iron jetpacks.

[crash-2022-06-02_12.24.09-client.txt](https://github.com/Sirttas/ElementalCraft/files/8825895/crash-2022-06-02_12.24.09-client.txt)

**To Reproduce**
1. Start flying with jetpack
2. Mine through the floor
3. Fly through the floor into view of the pure infuser
4. The game crashes

**Expected behavior**

**ModPack**
All The Mods 7 (ATM7)

**Comment by Sirttas** [comment]
This looks a lot like a known bug fixed in 4.4.3 and you are in 4.4.2, please update and retry.
