### ISSUE TITLE
Source nodes briefly flash when items are picked up (when item is in view)

### ISSUE THREAD

**Issue by GarthF** [Sirttas/ElementalCraft#88]
**Describe the bug**
When picking up items from the world, elementalcraft sources show up briefly through all resources. The resource must be visible for it to trigger the effect. Depending on distance, the nodes either show up as black or white. 

**To Reproduce**
1. Place a block on the the ground and throw items onto it while facing nodes, either directly or through any solid blocks.
2. When the items vaccum into your inventory, the nodes highlight.

**Expected behavior**
Nodes should not show up through solid materials or highlight in any way when picking up resources.

**ModPack**
Direwolf20 1.3.1
    1.18.2 - Forge 40.1.25 - 4.4.2
Vanilla with only Elementalcraft 
    1.18.2 - Forge 40.1.30 - 4.4.4

https://user-images.githubusercontent.com/13380578/171696645-5aa55784-5034-46cb-9331-4b807a8763ba.mp4

**Comment by GarthF** [comment]
Interestingly, it might only happen on first world load/gen... I reloaded a world I'm playing in and the flashing no longer occurs in that.

**Comment by Sirttas** [comment]
Fixed in 1.19-5.0.0
