### ISSUE TITLE
Crash on world load 1.18.2

### ISSUE THREAD

**Issue by pabthelamb** [Sirttas/ElementalCraft#89]
When I load the world, it crashes

https://www.toptal.com/developers/hastebin/raw/uvibewifol

1. Load world
2. Crash

**Expected behavior**
No crash

Custom pack

**Comment by Sirttas** [comment]
There is another mod messing with tags loading. I need more logs to understand what is hapening.

**Comment by rovenfaded** [comment]
World load also crashes for me. I can create new worlds just fine, but existing worlds cause problems (i remember the first crash happening when putting one of those elemental storage containers in my inventory. tried deleting inv, but problem persists). The logs seem to reference elementalcraft a lot, especially around the point where the crash happens.
Latest Log: https://pastebin.com/K6HXJmfY

**Comment by Sirttas** [comment]
> World load also crashes for me. I can create new worlds just fine, but existing worlds cause problems (i remember the first crash happening when putting one of those elemental storage containers in my inventory. tried deleting inv, but problem persists). The logs seem to reference elementalcraft a lot, especially around the point where the crash happens. https://pastebin.com/K6HXJmfY

There is literally forbidden and arcanus as the source of the stack trace.

**Comment by Sirttas** [comment]
Anyway I added a workaround for the initial crash.
