### ISSUE TITLE
Pure infusion not working

### ISSUE THREAD

**Issue by Diromir92** [Sirttas/ElementalCraft#9]
Hello,
i am playing through your mod and I can't do the pure infusion for creating pure crystalls... the process starts properly but it never results in pure crystals.
Maybe you can help me with that.
Best regards and keep healthy
Diromir

**Comment by Sirttas** [comment]
Hello,

Pure infusion consumes a huge amount of element at a huge rate, you need to use improved pipes to feed it.

**Comment by OmaiGrundles** [comment]
I actually was dealing with this exact issue earlier! Figured out how to get past it though!

Using the improved pipes will allow you to craft the pure crystal, but there is a lot of weirdness that happens that probably should be looked at when attempting to craft with normal pipes

-The craft starts, but only 'runs'(emits particles) for about 5 seconds. This is a much shorter amount of time than it takes to actually craft with the better pipes.
-After the particles stop, 1 of the 4 containers will still be extracted from and never stop until the pipe is disconnected.
-Removing and placing the center ingredient(and I think sometimes the outer ones) will cause the particles to appear (and the draining of the 3 other containers) again, but often for a much shorter time

overall, these weird interactions just left me confused for a couple hours until somebody told me about the better pipes.

**Comment by Sirttas** [comment]
Did it solved your problem ?
