### ISSUE TITLE
Game crashes when putting any type of elemental container in inventory

### ISSUE THREAD

**Issue by rovenfaded** [Sirttas/ElementalCraft#90]
Minecraft: 1.18.2
Forge: 40.1.51
Mod: elementalcraft-1.18.2-4.4.7.jar

Putting an elemental container from elementalcraft in my inventory crashes the game. This goes for any type/size container, whether it's the small ones or the big ones. The crash persists, unless the item is externally removed from the inventory (eg nbtexplorer)

1. Enter world
2. Open (creative) inventory
3. Take container of any type out of the creative tab
4. Put into hotbar
5. Crash

Crash Log:
https://pastebin.com/K6HXJmfY

**Comment by Sirttas** [comment]
It is caused by Forbiden and Arcanus.

**Comment by Sirttas** [comment]
Here is the issue I just opened on their tracker: https://github.com/stal111/Forbidden-Arcanus/issues/263

**Comment by Sirttas** [comment]
I still managed to find a workaroud, it is fixed in 4.4.8
