### ISSUE TITLE
Crash with Jewel of the Kirin attacking mob

### ISSUE THREAD

**Issue by Gorgok** [Sirttas/ElementalCraft#91]
**Describe the bug**
Add jewel of the kirin to armor/sword and hit a mob and it crashes.

**To Reproduce**
1. Put jewel of kirin on armor or weapon
2. Swing at a mob
3. Crash
4. See error https://pastebin.com/w5uW1ZHr

**Expected behavior**
Hit mob, do damage, not crash

**ModPack**
Direwolf20 1.18 1.5.1

Also tested on a clean pack with only:
Forge 40.1.47
dpanvil-1.18.2-3.4.1.jar
elementalcraft-1.18.2-4.4.8.jar
Patchouli-1.18.2-70.jar

**Comment by Sirttas** [comment]
That's seems to be an oversight on my end.

**Comment by Sirttas** [comment]
fixed inb 4.4.9
