### ISSUE TITLE
Crash on attempt to add two items to anvil

### ISSUE THREAD

**Issue by VentedSun** [Sirttas/ElementalCraft#92]
1.16.5
ATM Spellbound 2.2.7
elementalcraft-1.16.5-2.7.14.jar

Combining one item with an infusion and one without causes the game to lock up and crash out to desktop.

**Comment by Sirttas** [comment]
Can you provide a crash report please?

**Comment by Sirttas** [comment]
As you failed to provide a crash report and I cannot reproduce I'm closing this issue. Please open a new one with a crash report.
