### ISSUE TITLE
Fire container not turning a inert crystal into a fire crystal

### ISSUE THREAD

**Issue by cobaltlol** [Sirttas/ElementalCraft#93]
So i filled up 1 small container with fire element and then put a infuser on top and then placed a inert crystal and then it drained all the fire element from the container but i didnt get a fire crystal, ive tried several times but it still didnt work

**Comment by Sirttas** [comment]
What version are you on?
Are you piping element to the container?

**Comment by cobaltlol** [comment]
1.16.5 and yes

**Comment by Sirttas** [comment]
What modpack are you on? what other mods are installed.

**Comment by cobaltlol** [comment]
Modpack is Permafrost - Eyes of the storm

**Comment by Sirttas** [comment]
There is no reason this should not work, make sure your pipe is correctly setup as extracting from a side and inserting to the other.

**Comment by cobaltlol** [comment]
![2022-07-12_17 44 16](https://user-images.githubusercontent.com/109155765/178518138-8006e979-e942-404c-b0ee-18da44db02e8.png)
![2022-07-12_17 44 14](https://user-images.githubusercontent.com/109155765/178518164-dc1f2706-4f51-4b01-b143-385323eba2cf.png)
Am i doing it wrong? cause i was watching a video of another person doing this and it worked for him without problems

**Comment by Sirttas** [comment]
Right click the pipe section connected to the extractor, it should change shape.

**Comment by cobaltlol** [comment]
Thanks, seems to work now

**Comment by Sirttas** [comment]
No problem.
