### ISSUE TITLE
[1.18] MythicBotany Alf Tools cannot be infused

### ISSUE THREAD

**Issue by LuciusV** [Sirttas/ElementalCraft#97]
**Describe the bug**
While Botania Terrasteel tools can be infused normally, their upgrades from MythicBotany cannot.
Also, vanilla iron and Botania shears cannot be infused, although it makes sense for them to be, as they accept enchantments.

**To Reproduce**
1. Place Alfsteel tool into Element Infuser
2. Nothing happens

**Expected behavior**
Expected that tool receives infusion

**ModPack**
Direwolf20 1.18
Elementalcraft version: elementalcraft-1.18.2-4.4.9
MythicBotany version: MythicBotany-1.18.2-2.1.8

**Comment by Sirttas** [comment]
You need to add the tool to the tag `data/elementalcraft/tags/items/infusable/<tool>`.
