### ISSUE TITLE
Source Receptacle loosing NBT-Data on source placement

### ISSUE THREAD

**Issue by Schildos** [Sirttas/ElementalCraft#98]
**Describe the bug**
Source Receptacles lose NBT-Data after picking up and placing sources because of item changes

**To Reproduce**
1. Get a(n) (Improved) Source Receptacle 
2. Either add an enchantment or add an eternal Stella
3. Pickup a source
4. Place the source down again
5. Receptacle is damaged, unbreakable modifier or enchantments are gone

**Expected behavior**
NBT Data being retained upon node pickup

**ModPack**
ATM7

**Comment by Sirttas** [comment]
Receptacles should not be enchanted. Its a bug due to mods not checking if an item can be enchanted.
