### ISSUE TITLE
Breaking a reservoir in the wrong way may crash the game and prevent it from being loaded without save editing.

### ISSUE THREAD

**Issue by cimds** [Sirttas/ElementalCraft#99]
[Version: 4.4.17]
I was placing a 3x3 of fire element reservoirs and accidentally placed one one block too low, so I quickly broke it to place it in the right spot. Breaking the reservoir instantly crashed the game. Trying to enter the world crashes again, with the same error message:

java.lang.NullPointerException: Cannot invoke "sirttas.elementalcraft.block.container.reservoir.ReservoirBlockEntity.getElementStorage()" because the return value of "net.minecraft.world.level.Level.m_7702_(net.minecraft.core.BlockPos)" is null

I had to use Amulet MC to delete the reservoir, which made me able to load the world again. It appears that the reservoir somehow entered a state where half of it remained, with the crash happening after one half was broken and before the other half was updated and removed, The game tried to check the half reservoir's element level, it was null, and the game crashed because a number was expected. This may have been caused by an adjacent improved element pipe checking it at the exact right tick for this to occur, due to the reservoir being broken almost immediately after being placed in the wrong spot.

**Comment by Sirttas** [comment]
Should be fixed in 4.4.18
